name: Generate Cytoscape Graph JSON
on:
  push:
    paths:
      - docs/data/topics.json
      - scripts/generate-graph.py
  schedule:
    - cron: "30 08 * * 1"
  workflow_dispatch:
    input:
      tags:
        description: 'Test scenario tags'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install scikit-learn numpy

      - name: Generate Graph JSON
        run: python scripts/generate-gk-script.py

      - name: Commit Generated JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/data/graph.json
          git commit -m "Update Cytoscape graph JSON"
          git push
